# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Letrando' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Letrando
	pod 'lottie-ios'
  pod 'SwiftCharts'
  
  target 'LetrandoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LetrandoUITests' do
    # Pods for testing
  end

end
