name: Swift

on:
  pull_request:
     branches: [main, testflight, develop]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']
          
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Cache
      uses: actions/cache@v2
      with:
        id: spm-cache
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
        if: steps.spm-cache.outputs.cache-hit != 'true'
          ${{ runner.os }}-spm-
      
    - name: Build and Test
      run: |
        pwd
        swift package init --type library
        xcrun simctl list
        xcodebuild clean test -project Letrando/Letrando.xcodeproj -scheme Letrando -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        #bash <(curl -s https://codecov.io/bash)
      env: 
        destination: ${{ matrix.destination}}
        
